# Generated by Django 2.0.2 on 2019-01-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='photo',
            new_name='photo0',
        ),
        migrations.AddField(
            model_name='dish',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
