# Generated by Django 2.0.2 on 2019-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190110_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='portions',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
