# Generated by Django 2.0.2 on 2019-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='dish',
            name='added',
            field=models.DateField(blank=True, default='2019-11-08'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo0',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
