# Generated by Django 2.0.2 on 2019-02-12 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190212_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='added',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
