# Generated by Django 2.0.2 on 2019-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190212_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo0',
            field=models.ImageField(blank=True, default='static/logo.png', upload_to='images/'),
        ),
    ]
