# Generated by Django 2.0.2 on 2019-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190212_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo0',
            field=models.ImageField(blank=True, default='images/000empty.jpg', upload_to='images/'),
        ),
    ]
